config/routes.rb
Rails.application.routes.draw do
  resources :tweets, only: %i[index new create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :message, presence: true, length: { maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.order(created_at: :desc).all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to tweets_url, notice: 'Tweet was successfully created!'
    else
      render 'new'
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tweet was successfully deleted!'
  end

  private
  def tweet_params
    params.require(:tweet).permit(:message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AliTwitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container" style="padding-top: 16px">
      <div class="row justify-content-center">
        <div class="col-8">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/tweets/index.html.erb
<% if notice %>
<p class="alert alert-success"><%= notice %></p>
<% end %>

<div class="row justify-content-end" style="margin-bottom: 8px;">
  <%= link_to 'New Tweet', new_tweet_path, class: 'btn btn-primary' %>
</div>

<% @tweets.each do |tweet| %>
  <div class="row card" style="margin-bottom: 2px">
    <div class="card-body">
      <pre class="card-text"><%= tweet.message %></pre>
      <p class="text-muted"><small><%= tweet.created_at.to_formatted_s(:long) %></small></p>
      <%= link_to 'Delete', tweet, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
<% end %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= form_with(model: @tweet, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :message %>
    <%= form.text_area :message, class: "form-control", placeholder: "What's happening?" %>
  </div>

  <% if @tweet.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h5><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h5>

      <ul>
        <% @tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.submit class: "btn btn-primary", value: "Tweet!" %>
<% end %>